In [1]:
import torch
# Ctrl + Enter : 运行本单元
# Shift + Enter : 运行本单元，选中下一单元
# Alt + Enter : 运行本单元，在下面插入一单元

In [2]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

TypeError: 'torch.Size' object is not callable

In [3]:
x.shape

torch.Size([12])

In [4]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
torch.ones(3)

tensor([1., 1., 1.])

In [6]:
torch.zeros(3,4,5)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [9]:
torch.tensor([[1,2,4],[2,8,5],[2,4]])

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [8]:
torch.tensor([[1,2,4],[2,8,5],[2,4,9]])     #用torch定义一个张量
torch.randn(3,4)  #均值为0、标准差为1的标准⾼斯分布（正态分布）中随机采样
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y       #“按元素”⽅式计算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

tensor([[ 1.5664, -2.6469,  0.0089, -0.4534],
        [-0.2663,  0.5024, -0.3338,  1.8486],
        [-0.0578,  1.4049, -0.1033,  0.6275]])

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
x*3


tensor([ 3.,  6., 12., 24.])

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [10]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1.4,3.5,5],[2.0,3.1,2.5,6.1],[6.0,7.1,8.2,9.3]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)        #dim=0,1,2,3  按第0，1，2，3的方向连接 

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 2.0000,  1.4000,  3.5000,  5.0000],
         [ 2.0000,  3.1000,  2.5000,  6.1000],
         [ 6.0000,  7.1000,  8.2000,  9.3000]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  2.0000,  1.4000,  3.5000,  5.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000,  2.0000,  3.1000,  2.5000,  6.1000],
         [ 8.0000,  9.0000, 10.0000, 11.0000,  6.0000,  7.1000,  8.2000,  9.3000]]))

In [11]:
X==Y


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
x.sum()

tensor(15.)

In [13]:
a=torch.arange((3,1))

TypeError: arange(): argument 'end' (position 1) must be Number, not tuple

In [19]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
print("a=",a)
print("b=",b)


a= tensor([[0],
        [1],
        [2]])
b= tensor([[0, 1]])


In [16]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [26]:
X[1:3:,2:4]=9
X

tensor([[0., 1., 2., 3.],
        [4., 5., 9., 9.],
        [8., 9., 9., 9.]])

In [23]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
before=id(Y)
Y[:]=X+Y
id(Y)==before

True

In [32]:
import numpy as np

In [35]:
A=X.numpy()         #将tensor转化为numpy型
B=torch.tensor(A)   #将numpy型转化为tensor型
print(type(A),type(B))
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

<class 'numpy.ndarray'> <class 'torch.Tensor'>


(tensor([3.5000]), 3.5, 3.5, 3)

In [38]:
A=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
B=torch.tensor([[[1,6],[8,9]],[[11,61],[17,18]]])
print(A,B,"\n")
torch.cat((A,B),dim=0)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) tensor([[[ 1,  6],
         [ 8,  9]],

        [[11, 61],
         [17, 18]]]) 



tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 1,  6],
         [ 8,  9]],

        [[11, 61],
         [17, 18]]])