In [1]:
import torch
import pandas as pd
import os

In [2]:
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open (data_file,'w')as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,125770\n')
    f.write('NA,NA,140000\n')

In [3]:
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  125770
3       NaN   NaN  140000


In [4]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]  #iloc：读取的csv文件位置索引
inputs=inputs.fillna(inputs.mean())      #将inputs中缺少的数值，用同一列的均值替换“NaN”项。
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [5]:
#对于inputs中的类别值或离散值，我们将“NaN”视为一个类别。pandas可以自动将此列转换为两列（多列）“Alley_类别1”和“Alley_类别2”。
inputs=pd.get_dummies(inputs,dummy_na=True)  
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [6]:
#转化为张量形式
X,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 125770, 140000]))

In [7]:
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','name_age.csv')
with open(data_file,'w')as f:
    f.write('Name,Age,Weight,High,Power\n')
    f.write('1,18T,150,180,1110\n')
    f.write('2,NA,NA,180,1220\n')
    f.write('3,18,140,NA,2210\n')
    f.write('4,12,100,NA,1235\n')
    f.write('5,NA,NA,180,3245\n')
    f.write('6,25,160,NA,3641\n')
    f.write('7,28,120,NA,2210\n')

In [8]:
data=pd.read_csv(data_file)
print(data)

   Name  Age  Weight   High  Power
0     1  18T   150.0  180.0   1110
1     2  NaN     NaN  180.0   1220
2     3   18   140.0    NaN   2210
3     4   12   100.0    NaN   1235
4     5  NaN     NaN  180.0   3245
5     6   25   160.0    NaN   3641
6     7   28   120.0    NaN   2210


In [9]:
inputs,outputs=data.iloc[:,0:4],data.iloc[:,4]
r,c=inputs.shape
count=[0 for _ in range(c)]
print(r,c,count)
print(type(inputs.iloc[1,1]))
for i in range(c):  #列
    for j in range(r):  #行
        if pd.isna(inputs.iloc[j,i]) :  #判断是否为空
            count[i]+=1
Max=max(count)
index=count.index(Max)
print(count,Max,index)
cols=[i for i in range(index)]
cols.extend([index+1+i for i in range(c-index-1)])
print(cols)
inputs=data.iloc[:,cols]
print(inputs)        

7 4 [0, 0, 0, 0]
<class 'float'>
[0, 2, 2, 4] 4 3
[0, 1, 2]
   Name  Age  Weight
0     1  18T   150.0
1     2  NaN     NaN
2     3   18   140.0
3     4   12   100.0
4     5  NaN     NaN
5     6   25   160.0
6     7   28   120.0


In [10]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   Name  Weight  Age_12  Age_18  Age_18T  Age_25  Age_28  Age_nan
0     1   150.0       0       0        1       0       0        0
1     2     NaN       0       0        0       0       0        1
2     3   140.0       0       1        0       0       0        0
3     4   100.0       1       0        0       0       0        0
4     5     NaN       0       0        0       0       0        1
5     6   160.0       0       0        0       1       0        0
6     7   120.0       0       0        0       0       1        0


In [11]:
X,y=torch.tensor(inputs.values),torch.tensor(outputs.values)

In [12]:
X,y


(tensor([[  1., 150.,   0.,   0.,   1.,   0.,   0.,   0.],
         [  2.,  nan,   0.,   0.,   0.,   0.,   0.,   1.],
         [  3., 140.,   0.,   1.,   0.,   0.,   0.,   0.],
         [  4., 100.,   1.,   0.,   0.,   0.,   0.,   0.],
         [  5.,  nan,   0.,   0.,   0.,   0.,   0.,   1.],
         [  6., 160.,   0.,   0.,   0.,   1.,   0.,   0.],
         [  7., 120.,   0.,   0.,   0.,   0.,   1.,   0.]], dtype=torch.float64),
 tensor([1110, 1220, 2210, 1235, 3245, 3641, 2210]))