In [1]:
import torch 

In [3]:
x=torch.tensor(3.0)
y=torch.tensor(2.0)
x+y,x**y,x-y

(tensor(5.), tensor(9.), tensor(1.))

In [5]:
x=torch.arange(4)

In [6]:
x[3]

tensor(3)

In [7]:
len(x)

4

In [8]:
x.shape

torch.Size([4])

In [10]:
y=torch.arange(6).reshape((3,2))
y

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [11]:
len(y)

3

In [12]:
y.shape

torch.Size([3, 2])

In [15]:
A=torch.arange(20).reshape((4,5))
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [16]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [17]:
B=torch.tensor([[1,2,3],[2,3,4],[3,4,5]])
B,B.T

(tensor([[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]),
 tensor([[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]))

In [18]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [19]:
B>B.T

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [21]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [23]:
A=torch.arange(20,dtype=torch.float32).reshape(4,5)
B=A.clone()     #将A拷贝给B
A,A+B,id(A),id(B)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.,  8.],
         [10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.]]),
 1741831629064,
 1741831627544)

In [24]:
A*B

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.],
        [225., 256., 289., 324., 361.]])

In [25]:
a=2
X=torch.tensor([[[1,2,3,4],[4,5,6,7],[7,8,9,0]],[[1,4,7,0],[2,5,8,9],[3,6,9,1]]])
a+X,(a*X).shape

(tensor([[[ 3,  4,  5,  6],
          [ 6,  7,  8,  9],
          [ 9, 10, 11,  2]],
 
         [[ 3,  6,  9,  2],
          [ 4,  7, 10, 11],
          [ 5,  8, 11,  3]]]),
 torch.Size([2, 3, 4]))

In [26]:
A


tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [29]:
sum1=A.sum()
A.shape,A.sum()

(torch.Size([4, 5]), tensor(190.))

In [33]:
X=torch.arange(24).reshape(2,3,4)     #2页3行4列
A_sum_axis0=X.sum(axis=0)
X,A_sum_axis0,A_sum_axis0.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [34]:
X_sum_axis1=X.sum(axis=1)
X_sum_axis1

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [37]:
X_sum_axis01=X.sum(axis=[0,1])   #沿axis=0、1两个方向求和，求和后这两个方向的维度都消失
X, X_sum_axis01,  X_sum_axis01.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([60, 66, 72, 78]),
 torch.Size([4]))

In [44]:
X*1.0

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [48]:
a=X.mean()     #整型不能用，要浮点型
b=X.sum()/X.numel()    #numel求X中元素个数
a, b

(tensor(11.5000), tensor(11.5000))

In [51]:
a=X.mean(axis=0)
b=X.mean(axis=[0,1])
X, a, b

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.]]),
 tensor([10., 11., 12., 13.]))

In [57]:
sum_a=X.sum(axis=[0,1],keepdims=True)    #非降维求和

sum_a , sum_a.shape

(tensor([[[60., 66., 72., 78.]]]), torch.Size([1, 1, 4]))

In [58]:
X/sum_a

tensor([[[0.0000, 0.0152, 0.0278, 0.0385],
         [0.0667, 0.0758, 0.0833, 0.0897],
         [0.1333, 0.1364, 0.1389, 0.1410]],

        [[0.2000, 0.1970, 0.1944, 0.1923],
         [0.2667, 0.2576, 0.2500, 0.2436],
         [0.3333, 0.3182, 0.3056, 0.2949]]])

In [69]:
A=torch.arange(12,dtype=torch.float32).reshape(3,4)
sum_a1=A.sum(axis=1,keepdims=True)     #非降维求和
percent_axis1=A/sum_a1             #计算每个元素占他所在行的比列
A, sum_a1, percent_axis1

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 6.],
         [22.],
         [38.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895]]))

In [72]:
x=torch.arange(4,dtype=torch.float32)
y=torch.ones(4,dtype=torch.float32)
dot2=torch.dot(x,y)    #求点积
dot1=torch.sum(x*y)   #可以通过按元素相加在求和
x, y, dot2, dot1

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

In [78]:
A=torch.arange(12,dtype=torch.float32).reshape(3,4)
x=torch.tensor(4*[1],dtype=torch.float32)
product=torch.mv(A,x)     #矩阵-向量积（矩阵乘向量）
A, x, product

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([1., 1., 1., 1.]),
 tensor([ 6., 22., 38.]))

In [83]:
B=torch.ones(4,4)
torch.mm(A,B)    #矩阵A乘矩阵B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.,  6.],
         [22., 22., 22., 22.],
         [38., 38., 38., 38.]]))

In [87]:
A = torch.ones(4,9)
x = torch.tensor([4.0,3.0])   
#norm用于计算L2或F范数
l2=torch.norm(x)      #计算L2范数
f=torch.norm(A)       #计算F范数
l2, f

(tensor(5.), tensor(6.))

In [89]:
l1=torch.abs(x).sum()  #计算L1范数
l1

tensor(7.)

In [90]:
X = torch.arange(24).reshape(2,3,4)
len(X)

2