In [1]:
import torch
from torch import nn
from d2l import torch as d2l

def corr2d(X,k):
    h,w=k.shape
    Y=torch.zeros(X.shape[0]-h+1,X.shape[1]-w+1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j]=(X[i:i+h,j:j+w]*k).sum()
    return Y

In [2]:
X=torch.arange(9,dtype=torch.float32).reshape(3,3)
k=torch.arange(4,dtype=torch.float32).reshape(2,2)
corr2d(X,k)

tensor([[19., 25.],
        [37., 43.]])

In [3]:
class Conv2D(nn.Module):
    def __init__(self,kernel_size):
        super().__init__()
        self.weight=nn.Parameter(torch.rand(kernal_size))
        self.bias=nn.Parameter(torch.zeros(1))
    
    def forward(self,X):
        return corr2d(X,self.weight)+self.bias

In [4]:
X=torch.ones((6,8))
X[:,2:6]=0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [5]:
k=torch.tensor([[1.0,-1.0]])
Y=corr2d(X,k)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [6]:
corr2d(X.T,k)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
conv2d=nn.Conv2d(1,1,kernel_size=(1,2),bias=False)
X=X.reshape((1,1,6,8))
Y=Y.reshape((1,1,6,7))
lr=3e-2

for i in range(10):
    Y_hat=conv2d(X)
    l=(Y-Y_hat)**2
    conv2d.zero_grad()
    l.sum().backward()
    conv2d.weight.data[:] -= lr*conv2d.weight.grad
    if (i+1)%2==0:
        print(f'epoch:{i},loss:{l.sum()}:.3f')

epoch:1,loss:12.811315536499023:.3f
epoch:3,loss:3.3423144817352295:.3f
epoch:5,loss:1.049372911453247:.3f
epoch:7,loss:0.37619662284851074:.3f
epoch:9,loss:0.14509330689907074:.3f


In [9]:
conv2d.weight.data.reshape((1,2))

tensor([[ 1.0239, -0.9469]])

In [10]:
(1,1)+(2,3)

(1, 1, 2, 3)